<?php

class DetailResult
{
    public
        $Ico,
        $IcDPH,
        $Name,
        $Street,
        $StreetNumber,
        $ZipCode,
        $City,
        $Region,
        $District,
        $LegalForm,
        $OwnershipType,
        $EmployeeCount,
        $Activity,
        $Created,
        $Cancelled,
        $Url,
        $Warning,
        $WarningUrl,
        $CzNaceCode,
        $CzNaceText,
        $CzNaceDicision,
        $CzNaceGroup
    ;
}
?>