<?php

class BaseResult
{
    public
        $Ico,
        $RegisterNumberText,
        $Dic,
        $IcDPH,
        $Name,
        $Street,
        $StreetNumber,
        $ZipCode,
        $City,
        $Activity,
        $Created,
        $Cancelled,
        $SuspendedAsPerson,
        $Url,
        $Warning,
        $WarningUrl,
        $OrChange,
        $OrChangeUrl,
        $PaymentOrderWarning,
        $PaymentOrderUrl,
        $SkNaceCode,
        $SkNaceText,
        $SkNaceDivision,
        $SkNaceGroup
    ;
}
?>